In [1]:
import pandas as pd

In [69]:
pathway_df[pathway_df['pathway_mode']==6]

,pathway_id,from_stop_id,to_stop_id,pathway_mode,is_bidirectional,length,traversal_time,stair_count,max_slope,min_width,signposted_as,reversed_signposted_as,mode_description
8,A01_C01_104118,NODE_A01_C01_N_FG_UNPAID,NODE_A01_C01_N_FG_PAID,6,0,4.473432,5,NaN,NaN,NaN,NaN,NaN,Fare gate/turnstile
28,A01_C01_104138,NODE_A01_C01_S_FG_UNPAID,NODE_A01_C01_S_FG_PAID,6,0,4.560155,5,NaN,NaN,NaN,NaN,NaN,Fare gate/turnstile
46,A01_C01_104160,NODE_A01_C01_W_UNPAID,NODE_A01_C01_W_PAID,6,0,3.343283,5,NaN,NaN,NaN,NaN,NaN,Fare gate/turnstile
64,A01_C01_104178,NODE_A01_C01_E_FG_UNPAID,NODE_A01_C01_E_FG_PAID,6,0,3.407523,5,NaN,NaN,NaN,NaN,NaN,Fare gate/turnstile
107,A02_105117,NODE_A02_S_FG_UNPAID,NODE_A02_S_FG_PAID,6,0,3.520369,5,NaN,NaN,NaN,NaN,NaN,Fare gate/turnstile
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,N08_193009,NODE_N08_MZ_FG_UNPAID,NODE_N08_MZ_FG_PAID,6,0,12.943840,5,NaN,NaN,NaN,NaN,NaN,Fare gate/turnstile
2853,N09_194009,NODE_N09_MZ_FG_UNPAID,NODE_N09_MZ_FG_PAID,6,0,6.963581,5,NaN,NaN,NaN,NaN,NaN,Fare gate/turnstile
2871,N10_195001,NODE_N10_MZ_FG_UNPAID,NODE_N10_MZ_FG_PAID,6,0,16.438032,5,NaN,NaN,NaN,NaN,NaN,Fare gate/turnstile
2911,N11_196009,NODE_N11_MZ_FG_UNPAID,NODE_N11_MZ_FG_PAID,6,0,7.335465,5,NaN,NaN,NaN,NaN,NaN,Fare gate/turnstile
2945,N12_197016,NODE_N12_MZ_FG_UNPAID,NODE_N12_MZ_FG_PAID,6,0,7.361785,5,NaN,NaN,NaN,NaN,NaN,Fare gate/turnstile

In [70]:
folder_path = 'data/gtfs'
pathway_df = pd.read_csv(f'{folder_path}/pathways.txt')
pathway_df

pathway_modes = {
    1 : "Walkway",
    2 : "Stairs",
    3 : "Moving sidewalk/travelator",
    4 : "Escalator",
    5 : "Elevator",
    6 : "Fare gate/turnstile"
}

pathway_df['mode_description'] = pathway_df['pathway_mode'].map(pathway_modes)

folder_path = 'data/gtfs'
stops_df = pd.read_csv(f'{folder_path}/stops.txt')

bus_stops = stops_df[pd.to_numeric(stops_df['stop_id'], errors='coerce').notnull()]
bus_stops = bus_stops.dropna(axis=1, how='all')
bus_stops

rail_stops = stops_df[pd.to_numeric(stops_df['stop_id'], errors='coerce').isnull()]
rail_stops = rail_stops.dropna(axis=1, how='all')
rail_stops

,stop_id,stop_name,stop_desc,stop_lat,stop_lon,zone_id,location_type,parent_station,wheelchair_boarding,level_id
7542,ENT_A01_C01_E,Entrance B - 11Th and G Sts.,Entrance B - 11Th & G Sts,38.898061,-77.026783,10.0,2.0,STN_A01_C01,2.0,NaN
7543,ENT_A01_C01_N,Entrance A - 12Th and G Sts.,Entrance A - 12Th & G Sts,38.898482,-77.027894,10.0,2.0,STN_A01_C01,2.0,NaN
7544,ENT_A01_C01_N_EL,Entrance A - 12Th and G Sts. NW (Elevator),Entrance A Elevator - 12Th & G Sts,38.898922,-77.027923,10.0,2.0,STN_A01_C01,1.0,NaN
7545,ENT_A01_C01_S,Entrance C - 12Th and F Sts. NW,Entrance C - 12Th & F Sts,38.897146,-77.028592,10.0,2.0,STN_A01_C01,2.0,NaN
7546,ENT_A01_C01_W,Entrance D - 13Th and G Sts. NW,Entrance D - 13Th & G Sts,38.898012,-77.029371,10.0,2.0,STN_A01_C01,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...
9712,STN_N08,Herndon,NaN,38.952821,-77.385178,93.0,1.0,NaN,1.0,NaN
9713,STN_N09,Innovation Center,NaN,38.960881,-77.415638,94.0,1.0,NaN,1.0,NaN
9714,STN_N10,Washington Dulles International Airport,NaN,38.955786,-77.448189,95.0,1.0,NaN,1.0,NaN
9715,STN_N11,Loudoun Gateway,NaN,38.992040,-77.460685,96.0,1.0,NaN,1.0,NaN
9716,STN_N12,Ashburn,NaN,39.005196,-77.491434,97.0,1.0,NaN,1.0,NaN

In [71]:
pathway_df

,pathway_id,from_stop_id,to_stop_id,pathway_mode,is_bidirectional,length,traversal_time,stair_count,max_slope,min_width,signposted_as,reversed_signposted_as,mode_description
0,A01_C01_104110,ENT_A01_C01_N,NODE_A01_C01_N_ESC1_BT,4,0,104.891636,52,NaN,NaN,NaN,Metro Center Station,NaN,Escalator
1,A01_C01_104111,NODE_A01_C01_N_ESC1_BT,ENT_A01_C01_N,4,0,101.691656,51,NaN,NaN,NaN,NaN,NaN,Escalator
2,A01_C01_104112,ENT_A01_C01_N,NODE_A01_C01_N_ESC1_BT,2,1,106.260278,71,60.0,NaN,NaN,NaN,NaN,Stairs
3,A01_C01_104113,NODE_A01_C01_N_ESC1_BT,NODE_A01_C01_N_MZ,1,1,78.057195,17,NaN,NaN,NaN,NaN,12th & G Sts,Walkway
4,A01_C01_104114,ENT_A01_C01_N_EL,NODE_A01_C01_N_ELE1_TP,1,1,2.758169,1,NaN,NaN,NaN,Metro Center Station Elevator to Mezzanine,NaN,Walkway
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2958,N12_197029,NODE_N12_MZ_ESC2_BT,PLF_N12_SV_ASHBURN,1,1,89.529622,19,NaN,NaN,NaN,NaN,NaN,Walkway
2959,N12_197030,NODE_N12_MZ_ESC1_BT,PLF_N12_SV_ASHBURN,1,1,7.179357,2,NaN,NaN,NaN,NaN,NaN,Walkway
2960,N12_197031,NODE_N12_MZ_ESC1_BT,PLF_N12_SV_DOWNTOWN_LARGO,1,1,6.818868,1,NaN,NaN,NaN,NaN,NaN,Walkway
2961,N12_197032,PLF_N12_SV_DOWNTOWN_LARGO,PF_N12_C,1,1,6.693711,1,NaN,NaN,NaN,NaN,NaN,Walkway
2962,N12_197033,PLF_N12_SV_ASHBURN,PF_N12_C,1,1,7.869479,2,NaN,NaN,NaN,NaN,NaN,Walkway

In [21]:
def get_level_description(level_id):

    if pd.isna(level_id) or level_id == '':
        return 'Level Not specified'
    level_indicator = level_id.split('_')[-1]
    level_mapping = {
        'L0': 'Street Level',
        'L1': 'Mezzanine/Fare Control',
        'L2': 'Platform Level',
        'L3': 'Lower Platform/Deep Level',
        'UL1': 'Upper Level (Above Ground)',
    }
    
    return level_mapping.get(level_indicator, f'Unknown Level ({level_indicator})')

rail_stops['level_description'] = rail_stops['level_id'].apply(get_level_description)
rail_stops

,stop_id,stop_name,stop_desc,stop_lat,stop_lon,zone_id,location_type,parent_station,wheelchair_boarding,level_id,level_description
7542,ENT_A01_C01_E,Entrance B - 11Th and G Sts.,Entrance B - 11Th & G Sts,38.898061,-77.026783,10.0,2.0,STN_A01_C01,2.0,NaN,Level Not specified
7543,ENT_A01_C01_N,Entrance A - 12Th and G Sts.,Entrance A - 12Th & G Sts,38.898482,-77.027894,10.0,2.0,STN_A01_C01,2.0,NaN,Level Not specified
7544,ENT_A01_C01_N_EL,Entrance A - 12Th and G Sts. NW (Elevator),Entrance A Elevator - 12Th & G Sts,38.898922,-77.027923,10.0,2.0,STN_A01_C01,1.0,NaN,Level Not specified
7545,ENT_A01_C01_S,Entrance C - 12Th and F Sts. NW,Entrance C - 12Th & F Sts,38.897146,-77.028592,10.0,2.0,STN_A01_C01,2.0,NaN,Level Not specified
7546,ENT_A01_C01_W,Entrance D - 13Th and G Sts. NW,Entrance D - 13Th & G Sts,38.898012,-77.029371,10.0,2.0,STN_A01_C01,2.0,NaN,Level Not specified
...,...,...,...,...,...,...,...,...,...,...,...
9712,STN_N08,Herndon,NaN,38.952821,-77.385178,93.0,1.0,NaN,1.0,NaN,Level Not specified
9713,STN_N09,Innovation Center,NaN,38.960881,-77.415638,94.0,1.0,NaN,1.0,NaN,Level Not specified
9714,STN_N10,Washington Dulles International Airport,NaN,38.955786,-77.448189,95.0,1.0,NaN,1.0,NaN,Level Not specified
9715,STN_N11,Loudoun Gateway,NaN,38.992040,-77.460685,96.0,1.0,NaN,1.0,NaN,Level Not specified
9716,STN_N12,Ashburn,NaN,39.005196,-77.491434,97.0,1.0,NaN,1.0,NaN,Level Not specified

In [66]:
import pandas as pd
import networkx as nx

def build_graph(paths_df: pd.DataFrame, stops_df: pd.DataFrame) -> nx.DiGraph:
    """Directed graph for routing/traversal; includes all edges; respects is_bidirectional."""
    G = nx.DiGraph()
    for _, r in stops_df.iterrows():
        G.add_node(r["stop_id"], location_type=r.get("location_type"))

    for _, r in paths_df.iterrows():
        u, v = r["from_stop_id"], r["to_stop_id"]
        mode = int(r["pathway_mode"])
        bi   = int(r["is_bidirectional"])
        G.add_edge(u, v, pathway_id=r["pathway_id"], pathway_mode=mode, is_bidirectional=bi)
        if bi == 1:
            G.add_edge(v, u, pathway_id=r["pathway_id"], pathway_mode=mode, is_bidirectional=bi)
    return G

def seed_sets(stops_df: pd.DataFrame):
    """Entrances: location_type=2 and stop_id starts with ENT_. Platforms/boarding areas: 0 or 4 or empty."""
    entrances = set(
        stops_df.loc[
            (stops_df["location_type"] == 2) &
            (stops_df["stop_id"].str.upper().str.startswith("ENT_")),
            "stop_id"
        ]
    )
    platforms = set(
        stops_df.loc[
            (stops_df["location_type"].isin([0, 4])) | (stops_df["location_type"].isna()) | (stops_df["stop_id"].str.upper().str.startswith("PF_")),
            "stop_id"
        ]
    )
    return entrances, platforms

def reachable_without_modes(G: nx.DiGraph, sources: set, forbid_modes={6, 7}):
    """Forward reachability from sources, not traversing edges whose pathway_mode is 6 or 7 (fare/exit gates)."""
    sources = [s for s in sources if s in G]  
    seen = set()
    stack = list(sources)
    while stack:
        u = stack.pop()
        if u in seen:
            continue
        seen.add(u)
        for v in G.successors(u):
            if G[u][v].get("pathway_mode") in forbid_modes:
                continue
            stack.append(v)
    return seen

def build_and_partition(stops_df: pd.DataFrame, pathways_df: pd.DataFrame):

    G = build_graph(pathways_df, stops_df)

    entrances, platforms = seed_sets(stops_df)
    gate_modes = {6, 7}
    unpaid_nodes = reachable_without_modes(G, entrances, forbid_modes=gate_modes)
    paid_nodes   = reachable_without_modes(G, platforms, forbid_modes=gate_modes)

    node_side = {}
    for n in G.nodes:
        in_unpaid = n in unpaid_nodes
        in_paid   = n in paid_nodes
        if in_unpaid and not in_paid:
            node_side[n] = "UNPAID"
        elif in_paid and not in_unpaid:
            node_side[n] = "PAID"
        elif in_paid and in_unpaid:
            node_side[n] = "AMBIG"    
        else:
            node_side[n] = "UNKNOWN"  

    nodes_with_side = (
        pd.DataFrame({"stop_id": list(node_side.keys()), "side": list(node_side.values())})
        .merge(stops_df[["stop_id","location_type"]], on="stop_id", how="left")
    )

    paths = pathways_df.copy()
    paths["from_side"] = paths["from_stop_id"].map(node_side)
    paths["to_side"]   = paths["to_stop_id"].map(node_side)

    def categorize(row):
        mode = int(row["pathway_mode"])
        fs, ts = row["from_side"], row["to_side"]
        if mode == 7 and fs == "PAID" and ts == "UNPAID":
            return "exit_gate"
        if mode == 6 and fs != ts:
            return "cross_faregate"
        if fs == "UNPAID" and ts == "UNPAID":
            return "pregate_internal"
        if fs == "PAID"   and ts == "PAID":
            return "postgate_internal"
        return "mixed_non_gate"

    paths["side_category"] = paths.apply(categorize, axis=1)

    # # Buckets
    fare_boundary_edges = paths[paths["pathway_mode"].isin(gate_modes)].copy()
    pre_gate_edges      = paths[paths["side_category"] == "pregate_internal"].copy()
    post_gate_edges     = paths[paths["side_category"] == "postgate_internal"].copy()
    pre_gate_nodes      = nodes_with_side[nodes_with_side["side"] == "UNPAID"].copy()
    post_gate_nodes     = nodes_with_side[nodes_with_side["side"] == "PAID"].copy()

    # # Sanity checks
    # exit_bad_bidir = fare_boundary_edges[(fare_boundary_edges["pathway_mode"] == 7) &
    #                                      (fare_boundary_edges["is_bidirectional"] == 1)]
    # if len(exit_bad_bidir):
    #     print(f"Warning: {len(exit_bad_bidir)} exit gates are bidirectional; GTFS requires mode 7 to be unidirectional.")

    return {
        "G": G,
        "nodes_with_side": nodes_with_side,
        "paths_with_side": paths,
        "fare_boundary_edges": fare_boundary_edges,  
        "pre_gate_edges": pre_gate_edges,
        "post_gate_edges": post_gate_edges,
        "pre_gate_nodes": pre_gate_nodes,
        "post_gate_nodes": post_gate_nodes
    }


parts = build_and_partition(stops_df, pathway_df)
G = parts["G"]

parts["post_gate_nodes"]
parts["pre_gate_edges"]


full_pathway_df = parts["paths_with_side"]

In [67]:
# Integrate stops and pathways data
# Merge stops info for from_stop_id
from_stops = rail_stops.rename(columns={
    'stop_id': 'from_stop_id',
    'stop_desc': 'from_stop_desc',
    'level_id': 'from_level_id',
    'location_type': 'from_location_type'
}).copy()

# Merge stops info for to_stop_id
to_stops = rail_stops.rename(columns={
    'stop_id': 'to_stop_id',
    'stop_desc': 'to_stop_desc',
    'level_id': 'to_level_id',
    'location_type': 'to_location_type'
}).copy()

# Merge pathways with from_stops and to_stops
integrated = full_pathway_df.merge(from_stops, on='from_stop_id', how='left')
integrated = integrated.merge(to_stops, on='to_stop_id', how='left')

# Display key columns for analysis
integrated[['from_stop_id', 'from_stop_desc', 'to_stop_id', 'to_stop_desc', 'pathway_id', 'mode_description', 'side_category', 'from_level_id', 'to_level_id', 'from_location_type', 'to_location_type']]

,from_stop_id,from_stop_desc,to_stop_id,to_stop_desc,pathway_id,mode_description,side_category,from_level_id,to_level_id,from_location_type,to_location_type
0,ENT_A01_C01_N,Entrance A - 12Th & G Sts,NODE_A01_C01_N_ESC1_BT,Bottom of Escalator Between Street and Mezzanine,A01_C01_104110,Escalator,pregate_internal,NaN,A01_C01_L2,2.0,3.0
1,NODE_A01_C01_N_ESC1_BT,Bottom of Escalator Between Street and Mezzanine,ENT_A01_C01_N,Entrance A - 12Th & G Sts,A01_C01_104111,Escalator,pregate_internal,A01_C01_L2,NaN,3.0,2.0
2,ENT_A01_C01_N,Entrance A - 12Th & G Sts,NODE_A01_C01_N_ESC1_BT,Bottom of Escalator Between Street and Mezzanine,A01_C01_104112,Stairs,pregate_internal,NaN,A01_C01_L2,2.0,3.0
3,NODE_A01_C01_N_ESC1_BT,Bottom of Escalator Between Street and Mezzanine,NODE_A01_C01_N_MZ,Center Mezzanine Area,A01_C01_104113,Walkway,pregate_internal,A01_C01_L2,A01_C01_L2,3.0,3.0
4,ENT_A01_C01_N_EL,Entrance A Elevator - 12Th & G Sts,NODE_A01_C01_N_ELE1_TP,Top of Elevator Between Street and Mezzanine,A01_C01_104114,Walkway,pregate_internal,NaN,A01_C01_L0,2.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...
2958,NODE_N12_MZ_ESC2_BT,Bottom of Escalator/Stairs Between Mezzanine a...,PLF_N12_SV_ASHBURN,Silver Line Platform to Ashburn,N12_197029,Walkway,postgate_internal,N12_L1,N12_L1,3.0,3.0
2959,NODE_N12_MZ_ESC1_BT,Bottom of Escalator/Stairs Between Mezzanine a...,PLF_N12_SV_ASHBURN,Silver Line Platform to Ashburn,N12_197030,Walkway,postgate_internal,N12_L1,N12_L1,3.0,3.0
2960,NODE_N12_MZ_ESC1_BT,Bottom of Escalator/Stairs Between Mezzanine a...,PLF_N12_SV_DOWNTOWN_LARGO,Silver Line Platform to Downtown Largo,N12_197031,Walkway,postgate_internal,N12_L1,N12_L1,3.0,3.0
2961,PLF_N12_SV_DOWNTOWN_LARGO,Silver Line Platform to Downtown Largo,PF_N12_C,Silver Line to Downtown Largo | Silver Line to...,N12_197032,Walkway,postgate_internal,N12_L1,N12_L1,3.0,0.0
2962,PLF_N12_SV_ASHBURN,Silver Line Platform to Ashburn,PF_N12_C,Silver Line to Downtown Largo | Silver Line to...,N12_197033,Walkway,postgate_internal,N12_L1,N12_L1,3.0,0.0

In [ ]:
# read txt file into pandas dataframe
folder_path = '/Users/kldl947/Library/CloudStorage/OneDrive-AZCollaboration/Misc/DAMG 7374/Rail & Bus Combined GTFS Static'
route_df = pd.read_csv(f'{folder_path}/routes.txt')
route_df = route_df[route_df['route_type'] == 1].copy()
route_df